[build-system]
requires = ["setuptools>=67", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rev-cam"
version = "0.1.2"
description = "Low-latency Raspberry Pi reversing camera WebRTC server"
readme = "README.md"
authors = [{name = "RevCam Team"}]
requires-python = ">=3.11"
dependencies = [
    "aiortc>=1.5.0",
    "fastapi>=0.109",
    "uvicorn[standard]>=0.27",
    "numpy>=1.24",
    "pydantic>=2.5",
    "python-multipart>=0.0.6"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4"
]

dynamic = ["classifiers"]

[tool.setuptools.packages.find]
where = ["src"]
